export { default as Category } from './Categorys/Category';
export * from './Home/Benefits/components';
export * from './Home/Benefits';
export { default as Descubrí } from './Home/Descubrí/Descubrí';
export { default as Card } from './Home/Descubrí/components/Card';
export * from './Home/Header/components';
export * from './Home/Header';
export * from './Home/Offers/components/OfferCard';
export * from './Home/Offers/components';
export * from './Home/Offers';
export { default as OffersDay } from './Home/OffersDay/OffersDay';
export { default as TextCard } from './Home/OffersDay/components/TextCard';
export { default as PopularCategories } from './Home/PopularCategories/PopularCategories';
export * from './Home/PopularCategories/components/CardCategories';
export * from './Home/Subscribe/components';
export * from './Home/Subscribe';
export { default as Tiendas } from './Home/Tiendas/Tiendas';
export * from './Home/Tiendas/components';
export * from './Home';
export { default as Products } from './Product/Products';
export { default as ProductsAll } from './Product/ProductsAll';
export * from './index';
