export { default as Accesorios } from './Accesorios';
export { default as Belleza } from './Belleza';
export { default as Celular } from './Celular';
export { default as Cocina } from './Cocina';
export { default as Computer } from './Computer';
export { default as Games } from './Games';
export { default as Home } from './Home';
export { default as Joyas } from './Joyas';
export { default as Micro } from './Micro';
export { default as Souvenirs } from './Souvenirs';
export { default as Ticket } from './Ticket';
export * from './index';
